// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: proto/flowdispatch.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlowDispatch_Submit_FullMethodName = "/flowdispatch.FlowDispatch/Submit"
	FlowDispatch_Stream_FullMethodName = "/flowdispatch.FlowDispatch/Stream"
)

// FlowDispatchClient is the client API for FlowDispatch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FlowDispatch inbound gRPC gateway.
//
// URL = transport only — the service field in the message drives routing,
// matching the HTTP and WebSocket transports.
type FlowDispatchClient interface {
	// Submit is a unary RPC mirroring POST /v1/http.
	// Use for request/response services (TTS, future STT file upload).
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	// Stream is a bidirectional streaming RPC mirroring WS /v1/ws.
	// Use for streaming services (STT) and session-oriented connections.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamMessage], error)
}

type flowDispatchClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowDispatchClient(cc grpc.ClientConnInterface) FlowDispatchClient {
	return &flowDispatchClient{cc}
}

func (c *flowDispatchClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, FlowDispatch_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowDispatchClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FlowDispatch_ServiceDesc.Streams[0], FlowDispatch_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMessage, StreamMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowDispatch_StreamClient = grpc.BidiStreamingClient[StreamMessage, StreamMessage]

// FlowDispatchServer is the server API for FlowDispatch service.
// All implementations must embed UnimplementedFlowDispatchServer
// for forward compatibility.
//
// FlowDispatch inbound gRPC gateway.
//
// URL = transport only — the service field in the message drives routing,
// matching the HTTP and WebSocket transports.
type FlowDispatchServer interface {
	// Submit is a unary RPC mirroring POST /v1/http.
	// Use for request/response services (TTS, future STT file upload).
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	// Stream is a bidirectional streaming RPC mirroring WS /v1/ws.
	// Use for streaming services (STT) and session-oriented connections.
	Stream(grpc.BidiStreamingServer[StreamMessage, StreamMessage]) error
	mustEmbedUnimplementedFlowDispatchServer()
}

// UnimplementedFlowDispatchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlowDispatchServer struct{}

func (UnimplementedFlowDispatchServer) Submit(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedFlowDispatchServer) Stream(grpc.BidiStreamingServer[StreamMessage, StreamMessage]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedFlowDispatchServer) mustEmbedUnimplementedFlowDispatchServer() {}
func (UnimplementedFlowDispatchServer) testEmbeddedByValue()                      {}

// UnsafeFlowDispatchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlowDispatchServer will
// result in compilation errors.
type UnsafeFlowDispatchServer interface {
	mustEmbedUnimplementedFlowDispatchServer()
}

func RegisterFlowDispatchServer(s grpc.ServiceRegistrar, srv FlowDispatchServer) {
	// If the following call panics, it indicates UnimplementedFlowDispatchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlowDispatch_ServiceDesc, srv)
}

func _FlowDispatch_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowDispatchServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowDispatch_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowDispatchServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowDispatch_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FlowDispatchServer).Stream(&grpc.GenericServerStream[StreamMessage, StreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowDispatch_StreamServer = grpc.BidiStreamingServer[StreamMessage, StreamMessage]

// FlowDispatch_ServiceDesc is the grpc.ServiceDesc for FlowDispatch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlowDispatch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flowdispatch.FlowDispatch",
	HandlerType: (*FlowDispatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _FlowDispatch_Submit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _FlowDispatch_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/flowdispatch.proto",
}
