// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/flowdispatch.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubmitRequest mirrors the POST /v1/http JSON body.
type SubmitRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Service  string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Pool     string                 `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`
	Priority int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// TTS fields
	Text        string  `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Speaker     string  `protobuf:"bytes,5,opt,name=speaker,proto3" json:"speaker,omitempty"`
	Language    string  `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Speed       float32 `protobuf:"fixed32,7,opt,name=speed,proto3" json:"speed,omitempty"`
	Gain        float32 `protobuf:"fixed32,8,opt,name=gain,proto3" json:"gain,omitempty"`
	OutFormat   string  `protobuf:"bytes,9,opt,name=out_format,json=outFormat,proto3" json:"out_format,omitempty"`
	PhraseBreak bool    `protobuf:"varint,10,opt,name=phrase_break,json=phraseBreak,proto3" json:"phrase_break,omitempty"`
	// STT fields (future: unary file upload)
	Audio         []byte `protobuf:"bytes,11,opt,name=audio,proto3" json:"audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_proto_flowdispatch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowdispatch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_flowdispatch_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SubmitRequest) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *SubmitRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SubmitRequest) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

func (x *SubmitRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SubmitRequest) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *SubmitRequest) GetGain() float32 {
	if x != nil {
		return x.Gain
	}
	return 0
}

func (x *SubmitRequest) GetOutFormat() string {
	if x != nil {
		return x.OutFormat
	}
	return ""
}

func (x *SubmitRequest) GetPhraseBreak() bool {
	if x != nil {
		return x.PhraseBreak
	}
	return false
}

func (x *SubmitRequest) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

// SubmitResponse mirrors the POST /v1/http response.
type SubmitResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PoolUsed  string                 `protobuf:"bytes,1,opt,name=pool_used,json=poolUsed,proto3" json:"pool_used,omitempty"`
	Warning   string                 `protobuf:"bytes,2,opt,name=warning,proto3" json:"warning,omitempty"`
	ErrorCode string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMsg  string                 `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	// TTS result
	Audio []byte `protobuf:"bytes,5,opt,name=audio,proto3" json:"audio,omitempty"`
	// STT result
	Transcript    string `protobuf:"bytes,6,opt,name=transcript,proto3" json:"transcript,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_proto_flowdispatch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowdispatch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_flowdispatch_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResponse) GetPoolUsed() string {
	if x != nil {
		return x.PoolUsed
	}
	return ""
}

func (x *SubmitResponse) GetWarning() string {
	if x != nil {
		return x.Warning
	}
	return ""
}

func (x *SubmitResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SubmitResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *SubmitResponse) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *SubmitResponse) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

// StreamMessage is used for both directions on the Stream RPC,
// mirroring the WS /v1/ws message protocol.
type StreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "start", "stop", "ready", "result", "done", "error", "warning"
	// start fields (client → server)
	Service     string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	SessionType string `protobuf:"bytes,3,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`
	Pool        string `protobuf:"bytes,4,opt,name=pool,proto3" json:"pool,omitempty"`
	Priority    int32  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	// TTS start fields
	Text        string  `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Speaker     string  `protobuf:"bytes,7,opt,name=speaker,proto3" json:"speaker,omitempty"`
	Language    string  `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	Speed       float32 `protobuf:"fixed32,9,opt,name=speed,proto3" json:"speed,omitempty"`
	Gain        float32 `protobuf:"fixed32,10,opt,name=gain,proto3" json:"gain,omitempty"`
	OutFormat   string  `protobuf:"bytes,11,opt,name=out_format,json=outFormat,proto3" json:"out_format,omitempty"`
	PhraseBreak bool    `protobuf:"varint,12,opt,name=phrase_break,json=phraseBreak,proto3" json:"phrase_break,omitempty"`
	// Audio chunk (client → server, STT streaming)
	Audio []byte `protobuf:"bytes,13,opt,name=audio,proto3" json:"audio,omitempty"`
	// Result fields (server → client)
	ResultText string `protobuf:"bytes,14,opt,name=result_text,json=resultText,proto3" json:"result_text,omitempty"`
	Final      bool   `protobuf:"varint,15,opt,name=final,proto3" json:"final,omitempty"`
	// TTS audio result (server → client)
	ResultAudio []byte `protobuf:"bytes,16,opt,name=result_audio,json=resultAudio,proto3" json:"result_audio,omitempty"`
	// Error / warning fields (server → client)
	Code          string `protobuf:"bytes,17,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string `protobuf:"bytes,18,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_proto_flowdispatch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowdispatch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_proto_flowdispatch_proto_rawDescGZIP(), []int{2}
}

func (x *StreamMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StreamMessage) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *StreamMessage) GetSessionType() string {
	if x != nil {
		return x.SessionType
	}
	return ""
}

func (x *StreamMessage) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *StreamMessage) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *StreamMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *StreamMessage) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

func (x *StreamMessage) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *StreamMessage) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *StreamMessage) GetGain() float32 {
	if x != nil {
		return x.Gain
	}
	return 0
}

func (x *StreamMessage) GetOutFormat() string {
	if x != nil {
		return x.OutFormat
	}
	return ""
}

func (x *StreamMessage) GetPhraseBreak() bool {
	if x != nil {
		return x.PhraseBreak
	}
	return false
}

func (x *StreamMessage) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *StreamMessage) GetResultText() string {
	if x != nil {
		return x.ResultText
	}
	return ""
}

func (x *StreamMessage) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

func (x *StreamMessage) GetResultAudio() []byte {
	if x != nil {
		return x.ResultAudio
	}
	return nil
}

func (x *StreamMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_flowdispatch_proto protoreflect.FileDescriptor

const file_proto_flowdispatch_proto_rawDesc = "" +
	"\n" +
	"\x18proto/flowdispatch.proto\x12\fflowdispatch\"\xa5\x02\n" +
	"\rSubmitRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04pool\x18\x02 \x01(\tR\x04pool\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x18\n" +
	"\aspeaker\x18\x05 \x01(\tR\aspeaker\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x14\n" +
	"\x05speed\x18\a \x01(\x02R\x05speed\x12\x12\n" +
	"\x04gain\x18\b \x01(\x02R\x04gain\x12\x1d\n" +
	"\n" +
	"out_format\x18\t \x01(\tR\toutFormat\x12!\n" +
	"\fphrase_break\x18\n" +
	" \x01(\bR\vphraseBreak\x12\x14\n" +
	"\x05audio\x18\v \x01(\fR\x05audio\"\xb9\x01\n" +
	"\x0eSubmitResponse\x12\x1b\n" +
	"\tpool_used\x18\x01 \x01(\tR\bpoolUsed\x12\x18\n" +
	"\awarning\x18\x02 \x01(\tR\awarning\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg\x12\x14\n" +
	"\x05audio\x18\x05 \x01(\fR\x05audio\x12\x1e\n" +
	"\n" +
	"transcript\x18\x06 \x01(\tR\n" +
	"transcript\"\xdc\x03\n" +
	"\rStreamMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12!\n" +
	"\fsession_type\x18\x03 \x01(\tR\vsessionType\x12\x12\n" +
	"\x04pool\x18\x04 \x01(\tR\x04pool\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12\x18\n" +
	"\aspeaker\x18\a \x01(\tR\aspeaker\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\x12\x14\n" +
	"\x05speed\x18\t \x01(\x02R\x05speed\x12\x12\n" +
	"\x04gain\x18\n" +
	" \x01(\x02R\x04gain\x12\x1d\n" +
	"\n" +
	"out_format\x18\v \x01(\tR\toutFormat\x12!\n" +
	"\fphrase_break\x18\f \x01(\bR\vphraseBreak\x12\x14\n" +
	"\x05audio\x18\r \x01(\fR\x05audio\x12\x1f\n" +
	"\vresult_text\x18\x0e \x01(\tR\n" +
	"resultText\x12\x14\n" +
	"\x05final\x18\x0f \x01(\bR\x05final\x12!\n" +
	"\fresult_audio\x18\x10 \x01(\fR\vresultAudio\x12\x12\n" +
	"\x04code\x18\x11 \x01(\tR\x04code\x12\x10\n" +
	"\x03msg\x18\x12 \x01(\tR\x03msg2\x9b\x01\n" +
	"\fFlowDispatch\x12C\n" +
	"\x06Submit\x12\x1b.flowdispatch.SubmitRequest\x1a\x1c.flowdispatch.SubmitResponse\x12F\n" +
	"\x06Stream\x12\x1b.flowdispatch.StreamMessage\x1a\x1b.flowdispatch.StreamMessage(\x010\x01B+Z)github.com/Yooouuuuuuu/flowdispatch/protob\x06proto3"

var (
	file_proto_flowdispatch_proto_rawDescOnce sync.Once
	file_proto_flowdispatch_proto_rawDescData []byte
)

func file_proto_flowdispatch_proto_rawDescGZIP() []byte {
	file_proto_flowdispatch_proto_rawDescOnce.Do(func() {
		file_proto_flowdispatch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_flowdispatch_proto_rawDesc), len(file_proto_flowdispatch_proto_rawDesc)))
	})
	return file_proto_flowdispatch_proto_rawDescData
}

var file_proto_flowdispatch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_flowdispatch_proto_goTypes = []any{
	(*SubmitRequest)(nil),  // 0: flowdispatch.SubmitRequest
	(*SubmitResponse)(nil), // 1: flowdispatch.SubmitResponse
	(*StreamMessage)(nil),  // 2: flowdispatch.StreamMessage
}
var file_proto_flowdispatch_proto_depIdxs = []int32{
	0, // 0: flowdispatch.FlowDispatch.Submit:input_type -> flowdispatch.SubmitRequest
	2, // 1: flowdispatch.FlowDispatch.Stream:input_type -> flowdispatch.StreamMessage
	1, // 2: flowdispatch.FlowDispatch.Submit:output_type -> flowdispatch.SubmitResponse
	2, // 3: flowdispatch.FlowDispatch.Stream:output_type -> flowdispatch.StreamMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_flowdispatch_proto_init() }
func file_proto_flowdispatch_proto_init() {
	if File_proto_flowdispatch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_flowdispatch_proto_rawDesc), len(file_proto_flowdispatch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_flowdispatch_proto_goTypes,
		DependencyIndexes: file_proto_flowdispatch_proto_depIdxs,
		MessageInfos:      file_proto_flowdispatch_proto_msgTypes,
	}.Build()
	File_proto_flowdispatch_proto = out.File
	file_proto_flowdispatch_proto_goTypes = nil
	file_proto_flowdispatch_proto_depIdxs = nil
}
