// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/tts.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TtsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`                  //必要，服務名稱
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                                //必要，合成文字
	Outfmt        string                 `protobuf:"bytes,3,opt,name=outfmt,proto3" json:"outfmt,omitempty"`                            //輸出聲音格式，預設 mp3，支援 mp3, wav, pcm, pcm8(8K)
	VbrQuality    int64                  `protobuf:"varint,4,opt,name=vbr_quality,json=vbrQuality,proto3" json:"vbr_quality,omitempty"` //outfmt=mp3 時，音質設定，預設 4，0(好) ~ 9(差)
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`                        //主要語言，預設：zh-TW
	Phrbrk        bool                   `protobuf:"varint,8,opt,name=phrbrk,proto3" json:"phrbrk,omitempty"`                           //是否自動斷詞，預設：false
	Speaker       string                 `protobuf:"bytes,10,opt,name=speaker,proto3" json:"speaker,omitempty"`                         //主要語言語者，預設 Sharon
	Speed         float32                `protobuf:"fixed32,12,opt,name=speed,proto3" json:"speed,omitempty"`                           //主要語言語速，預設 1，範圍 0.5 ~ 2
	Gain          float32                `protobuf:"fixed32,14,opt,name=gain,proto3" json:"gain,omitempty"`                             //主要語言聲音大小，預設 1，範圍 0.5 ~ 4
	Token         string                 `protobuf:"bytes,23,opt,name=token,proto3" json:"token,omitempty"`                             //必要，賽微提供
	Uid           string                 `protobuf:"bytes,24,opt,name=uid,proto3" json:"uid,omitempty"`                                 //user unique id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtsRequest) Reset() {
	*x = TtsRequest{}
	mi := &file_proto_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtsRequest) ProtoMessage() {}

func (x *TtsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtsRequest.ProtoReflect.Descriptor instead.
func (*TtsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{0}
}

func (x *TtsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *TtsRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TtsRequest) GetOutfmt() string {
	if x != nil {
		return x.Outfmt
	}
	return ""
}

func (x *TtsRequest) GetVbrQuality() int64 {
	if x != nil {
		return x.VbrQuality
	}
	return 0
}

func (x *TtsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TtsRequest) GetPhrbrk() bool {
	if x != nil {
		return x.Phrbrk
	}
	return false
}

func (x *TtsRequest) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

func (x *TtsRequest) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *TtsRequest) GetGain() float32 {
	if x != nil {
		return x.Gain
	}
	return 0
}

func (x *TtsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TtsRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type TtsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtsResponse) Reset() {
	*x = TtsResponse{}
	mi := &file_proto_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtsResponse) ProtoMessage() {}

func (x *TtsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtsResponse.ProtoReflect.Descriptor instead.
func (*TtsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{1}
}

func (x *TtsResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_tts_proto protoreflect.FileDescriptor

const file_proto_tts_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/tts.proto\x12\rstreamservice\"\x9b\x02\n" +
	"\n" +
	"TtsRequest\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x16\n" +
	"\x06outfmt\x18\x03 \x01(\tR\x06outfmt\x12\x1f\n" +
	"\vvbr_quality\x18\x04 \x01(\x03R\n" +
	"vbrQuality\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12\x16\n" +
	"\x06phrbrk\x18\b \x01(\bR\x06phrbrk\x12\x18\n" +
	"\aspeaker\x18\n" +
	" \x01(\tR\aspeaker\x12\x14\n" +
	"\x05speed\x18\f \x01(\x02R\x05speed\x12\x12\n" +
	"\x04gain\x18\x0e \x01(\x02R\x04gain\x12\x14\n" +
	"\x05token\x18\x17 \x01(\tR\x05token\x12\x10\n" +
	"\x03uid\x18\x18 \x01(\tR\x03uid\"!\n" +
	"\vTtsResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2Q\n" +
	"\rStreamService\x12@\n" +
	"\x03TTS\x12\x19.streamservice.TtsRequest\x1a\x1a.streamservice.TtsResponse\"\x000\x01B*Z(github.com/Yooouuuuuuu/queuebridge/protob\x06proto3"

var (
	file_proto_tts_proto_rawDescOnce sync.Once
	file_proto_tts_proto_rawDescData []byte
)

func file_proto_tts_proto_rawDescGZIP() []byte {
	file_proto_tts_proto_rawDescOnce.Do(func() {
		file_proto_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tts_proto_rawDesc), len(file_proto_tts_proto_rawDesc)))
	})
	return file_proto_tts_proto_rawDescData
}

var file_proto_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_tts_proto_goTypes = []any{
	(*TtsRequest)(nil),  // 0: streamservice.TtsRequest
	(*TtsResponse)(nil), // 1: streamservice.TtsResponse
}
var file_proto_tts_proto_depIdxs = []int32{
	0, // 0: streamservice.StreamService.TTS:input_type -> streamservice.TtsRequest
	1, // 1: streamservice.StreamService.TTS:output_type -> streamservice.TtsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tts_proto_init() }
func file_proto_tts_proto_init() {
	if File_proto_tts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tts_proto_rawDesc), len(file_proto_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tts_proto_goTypes,
		DependencyIndexes: file_proto_tts_proto_depIdxs,
		MessageInfos:      file_proto_tts_proto_msgTypes,
	}.Build()
	File_proto_tts_proto = out.File
	file_proto_tts_proto_goTypes = nil
	file_proto_tts_proto_depIdxs = nil
}
